# basic options
title: Blackdragonpencraft
author: Michael Burke
email: maburke@uncg.edu
description: Gallery and Comics by Obi
github_username:  maburke

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
